<a href="https://colab.research.google.com/github/PDM-15/AML-2026/blob/master/ML_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment - 2

1.Create a constant array that prints "[[ 7.  7.], [ 7.  7.]]"

In [ ]:
arr1 = np.array([[7,7],[7,7]])
arr1.astype('f')

array([[7., 7.],
       [7., 7.]], dtype=float32)

2. Create an array filled with random values that might print "[[ 0.91940167  0.08143941],[ 0.68744134  0.87236687]]

In [ ]:
arr2 = np.random.randint(1,4,5)
arr2.astype('f')

array([3., 3., 2., 3., 2.], dtype=float32)

3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array
Number of elements
Shape
Dimension
Data type

In [ ]:
arr3 = np.arange(10,50,1)
arr3.resize(4,10)

print(arr3, len(arr3), arr3.shape, arr3.dtype, arr3.shape,arr3.ndim, sep = " | ")


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] | 4 | (4, 10) | int64 | (4, 10) | 2


4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [ ]:
arr4 = np.zeros((1,10))
arr5 = np.ones((3,3))
arr6 = np.ones((4,4))
matrix1 = np.matrix(arr6)
arr7 = np.arange(5,50,5)

print(arr4)
print(arr5)
print(arr7)
print(matrix1)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25 30 35 40 45]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4

Display the shape and ndim of each result.

In [ ]:
arr8 = np.arange(1,25)

a = arr8.reshape(4,6)
b = arr8.reshape(6,4)
c = arr8.reshape(2,3,4)

print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)


(4, 6) 2
(6, 4) 2
(2, 3, 4) 3


6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element
Last element
Third element
First four elements
Last three elements

In [ ]:
marks = np.array([78,85,92,67,88,73,95,81])
print(marks[0], marks[-1], marks[2], marks[0:3], marks[-3:])

78 81 92 [78 85 92] [73 95 81]


7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b
a - b
a * b
a / b
Square of every element in a

In [ ]:
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:

Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [ ]:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

Total_salary = np.sum(salary)
Avg_salary = np.mean(salary)
Highest_salary = np.max(salary)
Lowest_salary = np.min(salary)
Median_salary = np.median(salary)
Std_dev = np.std(salary)

print(Total_salary)
print(Avg_salary)
print(Highest_salary)
print(Lowest_salary)
print(Median_salary)
print(Std_dev)

290000
36250.0
50000
25000
35000.0
8317.902379807063


9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

Using NumPy boolean indexing, find:

Marks greater than 75
Marks between 50 and 80
Number of students who scored below 50
Percentage of students who scored 60 or above

Do not use a Python for loop.


In [ ]:
marks = np.array([45,78,89,32,67,90,55,76,41,84])

print(marks[marks>75])
print(marks[(marks>50) & (marks<80)])
print(marks[marks<50])
print(np.mean(marks>=60)*100)


[78 89 90 76 84]
[78 67 55 76]
[45 32 41]
60.0


10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

Calculate:

Total marks of each student
Average marks of each student
Average marks in each subject
Student with the highest total
Highest mark in each subject.

In [ ]:
marks = np.array([[80,75,90], [65,70,72], [88,92,85], [55,60,58]])

tot_marks = np.sum(marks, axis=1)
avg_marks = np.mean(marks, axis=1)
avg_sub = np.mean(marks, axis=0)
highest_tot = np.argmax(tot_marks)
highest_eachsub = np.max(marks, axis=0)

print(tot_marks)
print(avg_marks)
print(avg_sub)
print(highest_tot)
print(highest_eachsub)

[245 207 265 173]
[81.66666667 69.         88.33333333 57.66666667]
[72.   74.25 76.25]
2
[88 92 90]


11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

Matrix addition
Element-wise multiplication
Matrix multiplication
Transpose of A.

explain the difference between:
A * B and A @ B


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A+B)
print(A*B)
print(A@B)
print(A.T)


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


12. Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

Find:

Mean temperature
Maximum and minimum temperatures
Number of days above the average temperature
Temperatures greater than 34°C
Difference between maximum and minimum
Standard deviation


In [ ]:
temperature = np.array([31, 32, 33, 35, 36, 34, 32, 30, 29, 31, 33, 35, 37, 36])

print(temperature.mean())
print(temperature.max(), temperature.min())
print(temperature[temperature>temperature.mean()])
print(temperature[temperature>34])
print(temperature.max() - temperature.min())
print(temperature.std())

33.142857142857146
37 29
[35 36 34 35 37 36]
[35 36 35 37 36]
8
2.356060357495806


13. Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

Determine:

Total annual sales
Average monthly sales
Month with the highest sales
Month with the lowest sales
Number of months with sales above ₹20,000
Percentage increase from January to December

In [ ]:
import numpy as np

sales = np.array([12000, 15000, 17000, 14000, 18000, 21000, 19000, 22000,25000,23000, 26000, 28000])

total_annual_sales = np.sum(sales)
avg_monthly_sales = np.mean(sales)
mth_hig_sales = np.max(sales)
mth_low_sales = np.min(sales)
sal_above_20k = len(sales[sales>20000])
percentage_increase = (sales[-1] - sales[0])/sales[0] * 100

print(total_annual_sales, avg_monthly_sales, mth_hig_sales, mth_low_sales, sal_above_20k, percentage_increase, sep = " || ")


240000 || 20000.0 || 28000 || 12000 || 6 || 133.33333333333331


14. Consider marks of five students in four subjects:

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

Write a NumPy program that calculates:

Total marks of every student
Average of every student
Average mark for every subject
Highest-scoring student
Lowest-scoring student
Students whose average is greater than 80
Overall class average

Then assign a performance category based on average:

|  Average | Category          |
| -------: | ----------------- |
|     ≥ 85 | Excellent         |
| 70–84.99 | Good              |
| 50–69.99 | Average           |
|     < 50 | Needs Improvement |

Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

In [ ]:
import numpy as np

marks = np.array([ [78, 85, 90, 88], [65, 70, 72, 68], [92, 88, 95, 91], [55, 60, 58, 62], [80, 75, 82, 79] ])

total_marks = np.sum(marks, axis=1)
avg_stu = np.mean(marks, axis=1)
avg_mark = np.mean(marks, axis=0)
high_score = np.argmax(marks, axis=1)
low_score = np.argmin(marks, axis=0)
class_avg = np.mean(marks)

print(f"Total marks of every student:{total_marks} \n Average of every student:{avg_stu}\n Average mark for every subject:{avg_mark}\n Highest-scoring student:{high_score}\n Lowest-scoring student:{low_score}\n Students whose average is greater than 80:{len(avg_stu[avg_stu>80])}\n Overall class average: {class_avg}")

conditions = [(avg_stu>=85), (avg_stu>=70), (avg_stu>=50)]
choice = ["Excellent","Good", "Average"]
result = np.select(conditions, choice, default = "Needs Improvement")

print(result)

Total marks of every student:[341 275 366 235 316] 
 Average of every student:[85.25 68.75 91.5  58.75 79.  ]
 Average mark for every subject:[74.  75.6 79.4 77.6]
 Highest-scoring student:[2 2 2 3 2]
 Lowest-scoring student:[3 3 3 3]
 Students whose average is greater than 80:2
 Overall class average: 76.65
['Excellent' 'Average' 'Excellent' 'Average' 'Good']


15. Generate 20 random integers between 1 and 100

In [ ]:
import random

random_integers = [random.randint(1,100) for _ in range(20)]
print(random_integers)

[20, 76, 59, 42, 50, 14, 61, 94, 66, 27, 11, 60, 60, 22, 31, 84, 28, 50, 7, 75]


16. Find all even numbers from the generated array

In [ ]:
#arr = np.array([20, 76, 59, 42, 50, 14, 61, 94, 66, 27, 11, 60, 60, 22, 31, 84, 28, 50, 7, 75])
for i in range(20):
  if random_integers[i]%2 == 0:
    print(random_integers[i])
  else:
    pass


20
76
42
50
14
94
66
60
60
22
84
28
50


17. Replace values below 50 with 0

In [ ]:
arr = np.array(random_integers)
arr[arr<50] = 0
print(arr)


[ 0 76 59  0 50  0 61 94 66  0  0 60 60  0  0 84  0 50  0 75]


18. Sort the array in ascending and descending order

In [ ]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[ 0  0  0  0  0  0  0  0  0 50 50 59 60 60 61 66 75 76 84 94]
[94 84 76 75 66 61 60 60 59 50 50  0  0  0  0  0  0  0  0  0]


19. Find unique values and their frequencies

In [ ]:
values, frequencies = np.unique(arr, return_counts = True)
print(values, frequencies)

[ 0 50 59 60 61 66 75 76 84 94] [9 2 1 2 1 1 1 1 1 1]


20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.


In [ ]:
import numpy as np

matrix1 = np.matrix([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

row_mean = np.mean(matrix1, axis = 1)
col_mean = np.mean(matrix1, axis = 0)

print(row_mean,"\n", col_mean)

[[ 3.]
 [ 8.]
 [13.]
 [18.]
 [23.]] 
 [[11. 12. 13. 14. 15.]]


21. Take your own example to normalize an array

In [ ]:
arr = np.array([1,2,3,4,5,6])

arr_min = np.min(arr)
arr_max = np.max(arr)
normalised_arr = (arr - arr_min)/(arr_max - arr_min)

print(normalised_arr)

[0.  0.2 0.4 0.6 0.8 1. ]


22. use your own data to standardize an array

In [ ]:
std_arr = (arr - np.mean(arr))/np.std(arr)

print(std_arr)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100

In [ ]:
import random

marks = [random.randint(0,100) for i in range(100)]
count1 = count2 = count3 = count4 = 0;

for i in range(100):
  if marks[i] > 0 & marks[i] <= 39:
    count1 += 1
  elif marks[i] >= 40 & marks[i] <= 59:
    count2 += 1
  elif marks[i] >=60 & marks[i] <=79:
    count3 += 1
  else:
    count4 += 1

print(marks)
print(f"Within range 0 - 39: {count1} Within range 40 - 59: {count2} Within range 60 - 79: {count3} Within range 80 - 100: {count4}")

[35, 67, 34, 45, 50, 44, 70, 19, 93, 53, 18, 28, 60, 89, 45, 74, 26, 29, 28, 6, 13, 66, 21, 37, 78, 34, 35, 100, 61, 1, 5, 69, 65, 47, 44, 19, 30, 40, 18, 100, 15, 51, 44, 35, 35, 41, 21, 11, 100, 0, 99, 32, 91, 74, 69, 28, 89, 5, 28, 58, 29, 44, 26, 55, 93, 64, 96, 5, 57, 49, 74, 62, 2, 83, 46, 91, 81, 15, 54, 67, 64, 43, 62, 20, 88, 30, 74, 29, 46, 28, 83, 30, 55, 83, 48, 5, 78, 16, 50, 20]
Within range 0 - 39: 99 Within range 40 - 59: 1 Within range 60 - 79: 0 Within range 80 - 100: 0


24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array

In [ ]:
import time
import numpy as np

# Number of elements (1 million)
size = 1_000_000

# --- 1. Python List Approach ---
# Creating two lists of 1 million items
list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
# Element-wise multiplication using a list comprehension
list_result = [a * b for a, b in zip(list_a, list_b)]
list_duration = time.time() - start_time

print(f"Python list time: {list_duration:.6f} seconds")


# --- 2. NumPy Array Approach ---
# Creating two NumPy arrays of 1 million items
array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
# Element-wise multiplication using a vectorized operation
array_result = array_a * array_b
array_duration = time.time() - start_time

print(f"NumPy array time: {array_duration:.6f} seconds")


# --- 3. Speed Factor ---
speedup = list_duration / array_duration
print(f"NumPy is approximately {speedup:.1f}x faster!")

Python list time: 0.047691 seconds
NumPy array time: 0.002472 seconds
NumPy is approximately 19.3x faster!
