<a href="https://colab.research.google.com/github/PDM-15/AML-2026/blob/master/MLLab_11Aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

11.08.2026

In [ ]:
import numpy as np #to import numpy library

mylist = np.array([1,2,3,4]) #creation of ndarray

y = np.array([4,5,6])

m = np.array([[7,8],[9,10],[11,12]])
m.shape #check array dimension

(3, 2)

In [ ]:
n = np.arange(0,30,2) #creates an ndarray with a specified interval
n.reshape(3,5) #reshape array


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
lspace = np.linspace(0,10,9)#evenly spaced numbers
lspace.resize(3,3) # resize the whole matrix
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,4)) #provides ones matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,3)) #zeros matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(4) #diagonal matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
matrix1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]]) #construction of matrix
matrix1
#print(np.diag(matrix1)) #diagonal elements
#print(np.diag(matrix1,1)) #elements above diagonal elements
print(np.diag(matrix1,-1)) #elements below diagonal elements

[3]


In [ ]:
np.array([1,2,3] * 3) # repeat whole list thrice
np.repeat([1,2,3], 3) #repeat individual elements thrice

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.vstack([matrix1, 2*matrix1]) # vertical stacking of a matrix
np.hstack([matrix1, 2*matrix1]) #horizontal stacking of a matrix

matrix([[ 1,  2,  3,  2,  4,  6],
        [ 4,  5,  6,  8, 10, 12],
        [ 7,  8,  9, 14, 16, 18]])

In [ ]:
x = np.array([1,2,3])
y = np.array([1,4,6])

print(x+y) #elementwise addition of arrays
print(x-y) #elementwise subtraction of arrays
print(x*y) #elementwise multiplication of elements
print(x@y) #elementwise addition of the product array
print(x/y) #elementwise division of array
print(x**2) #elementwise square of the array
print(x.dot(y)) #dot product



[2 6 9]
[ 0 -2 -3]
[ 1  8 18]
27
[1.  0.5 0.5]
[1 4 9]
27


In [ ]:
len(x) #length of the array

z = np.array([[1,2,3],[4,5,6]])
z.T #transpose of the array
z.T.shape #shape of the transpose
z.dtype #type of the array

z.astype('f') # convert the array into float



3
21


In [ ]:
z.sum() #sum of all elements
z.max() #max of all elements
z.min() #min of all elements

z.mean() #mean value of the array
z.std() #find out the std deviation of the elements
z.argmax() #returns the index of the max element in the array
z.argmin() #returns the index of the min element in the array


np.int64(0)

In [ ]:
s = np.arange(100) #creates an array of a given range
s.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s = np.arange(6)**2 #creates an array of squares within the given range
print(s)

s[-1] #indexing on array
s[1:5] #printing values of the arrayin the specified range
s[-2:] #from last but oneth element and move till the end
s[-1::-2] #from last element, go upto the start in steps of 2

[ 0  1  4  9 16 25]


array([25,  9,  1])

In [ ]:
a = np.arange(100)
a.resize(10,10) #resize into desired no. of rows and columns

a[3,4] #rows and columns
a[2,1:4]
a[3,3:6]
a[:3,:-1]
a[-1, ::2] #row columns and steps
a[a>30] #elements greater than 30
a[a>50] = 50 # assigning particular range of values into a value


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [ ]:
a2 = a[:4, :4] #instance of a
a2[:] = 0 #overwrites values in a

a_copy = a.copy() # to overcome the overwrite problem use copy
a_copy[:] = 10 #even if modified, doesnt overwrite the original


array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [ 0,  0,  0,  0, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [ ]:
test = np.random.randint(0,10,(4,3))

for row in test: #used to loop through the rows
  print(row)

for i in range(len(test)):
  print(test[i])

for i, row in enumerate(test): #iterate by row and index
  print('row', i, 'is', row)



[1 5 4]
[1 1 8]
[4 5 0]
[6 8 9]
[1 5 4]
[1 1 8]
[4 5 0]
[6 8 9]
row 0 is [1 5 4]
row 1 is [1 1 8]
row 2 is [4 5 0]
row 3 is [6 8 9]


In [ ]:
test2 = test**2
test2

array([[ 1, 25, 16],
       [ 1,  1, 64],
       [16, 25,  0],
       [36, 64, 81]])

In [ ]:
for i,j in zip(test, test2):
  print(i,'+', j, '=', i+j)

[1 5 4] + [ 1 25 16] = [ 2 30 20]
[1 1 8] + [ 1  1 64] = [ 2  2 72]
[4 5 0] + [16 25  0] = [20 30  0]
[6 8 9] + [36 64 81] = [42 72 90]


In [ ]:
marks = np.array([[80,75,90],
                  [65,70, 72],
                  [88,92,85],
                  [55,60,58]])

st_totalmarks = np.sum(marks, axis=1) # axis 0 is column and axis 1 is row
st_minmarks = np.min(marks, axis=0)
st_maxmarks = np.max(marks, axis=1)
st_mean = np.mean(marks,axis=1)
st_highscorer = np.argmax(st_totalmarks)

st_highscorer

np.int64(2)