<a href="https://colab.research.google.com/github/PDM-15/AML-2026/blob/master/MLLab3_18Aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

18.08.2026

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

data = pd.read_csv("drive/My Drive/Dataset/Data.csv") #if using excel we need to use read_excel
dataset = data # Loading data

X = dataset.iloc[::-1].values #For independent data
dataset.head() #First five values of the dataset
dataset.tail() #Last five values of the dataset

dataset.shape
dataset.columns #Number of columns in the dataset
dataset.dtypes # Datatype of the dataset
dataset.info() #details of the dataset
dataset.describe() # Description of numeric values
dataset.isnull().sum() #To check if the dataset is having null values
dataset.duplicated().sum() #To check if duplicate values are present in the dataset


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


np.int64(0)

In [ ]:
#Split independent variables
X = dataset.iloc[:,:-1]
X

#Split dependent variables
y = dataset.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#Taking care of missing data
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #Object of Simple Imputer Class

imputer = imputer.fit(X.iloc[:,1:3]) # Used to calculate the mean value for columns  1 and 3
X.iloc[:, 1:3] = imputer.transform(X.iloc[:, 1:3]) # Fills missing value
X

,Country,Age,Salary
0,France,44.000000,72000.000000
1,Spain,27.000000,48000.000000
2,Germany,30.000000,54000.000000
3,Spain,38.000000,61000.000000
4,Germany,40.000000,63777.777778
5,France,35.000000,58000.000000
6,Spain,38.777778,52000.000000
7,France,48.000000,79000.000000
8,Germany,50.000000,83000.000000
9,France,37.000000,67000.000000


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder #Column transfer function is done by Onehotencoder to assign a value to string without bias
labelencoder_X = LabelEncoder() #LabelEncoder object
X.iloc[:,0] = labelencoder_X.fit_transform(X.iloc[:,0]) #Fit converts string to a code, transform used to map the values back to the corresponding string
print(X)

  Country        Age        Salary
0       0  44.000000  72000.000000
1       2  27.000000  48000.000000
2       1  30.000000  54000.000000
3       2  38.000000  61000.000000
4       1  40.000000  63777.777778
5       0  35.000000  58000.000000
6       2  38.777778  52000.000000
7       0  48.000000  79000.000000
8       1  50.000000  83000.000000
9       0  37.000000  67000.000000


In [ ]:
from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder = "passthrough")
X = ct.fit_transform(X)
X.astype(int)

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [ ]:
#Encoding the dependent variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#Split data into Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 45)


X_test

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04]])

In [ ]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])